<?php

	$labels = array();

	$labels['alias'] = 'alias';
	$labels['Alias'] = 'Alias';
	$labels['usernotallowed'] = 'You\'re not allowed to create aliases.';
	$labels['disallowedcharacters'] = 'E-mail cannot contain following characters: %s.';
	$labels['domainnotallowed'] = 'Domain "%s" is not allowed.';
	$labels['identitynamenotavailable'] = 'Identity name is not available.';
	$labels['maxidentitynumberreached'] = 'Maximum identity number reached.';
	$labels['useroridentityexists'] = 'User or identity "%s" already exists.';
	$labels['cantdeletelockedalias'] = 'Alias is locked until %s.';

?>