<?php

	$labels = array();

	$labels['alias'] = 'псевдоним';
	$labels['Alias'] = 'Псевдоним';
	$labels['usernotallowed'] = 'Вам запрещено создавать псевдонимы.';
	$labels['disallowedcharacters'] = 'Адрес не может содержать следующие символы: %s.';
	$labels['domainnotallowed'] = 'Домен "%s" недоступен.';
	$labels['identitynamenotavailable'] = 'Выбранный адрес недоступен.';
	$labels['maxidentitynumberreached'] = 'Достигнуто максимально допустимое количество профилей.';
	$labels['useroridentityexists'] = 'Пользователь или псевдоним с адресом "%s" уже существует.';
	$labels['cantdeletelockedalias'] = 'Псевдоним заблокирован до %s.';

?>